---
- name: Realizar cordon e drenar o node
  include_tasks: drain.yml

- name: Atualizar o sistema operacional
  include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: Remover cordon e desdrenar
  include_tasks: undrain.yml